### ISSUE TITLE
Small, pedantic nitpick - correct spelling of "Continuously"

### ISSUE THREAD

**Issue by ngolshan** [TypQxQ/Query-Endstop-Continuesly-in-Klipper#1]
A really minor thing that's probably very annoying to change at this point, but: 

the correct spelling of the word is "Continuously", rather than "Continuesly". 

Spelling error does not affect the functionality of the extension, which works great 👍🏼

**Comment by TypQxQ** [comment]
Thank you! I will change it where I can 😄
